### ISSUE TITLE
数据问题!!!

### ISSUE THREAD

**Issue by XuyangPan** [Lantian-Lance-Zhang/DCAT#3]

**Comment by XuyangPan** [comment]
数据集在哪里啊，怎么不完整呢

**Comment by lancezhang04** [comment]
Hi, I worked on this project two years ago as an intern for Aitrox Technology in Shanghai. If I recall correctly, the dataset was collected from partner hospitals and stored on dedicated company servers. Unfortunately I do not currently have access to these servers (it's been a while).
